### PR TITLE
[WIP] Use the full context in diff.

### PR DESCRIPTION
**Pull request by isaksamsten**
I updated to code to use the full context of the file in the diff window. I don't think this is ready to merge as-is, but could possibly be a way forward?

I don't really know the Neovim API so the changes might be sub-optimal and somewhat ugly, but in my tests it seems to work.

[Screencast](https://imgur.com/YQzWGP7)

### CODE REVIEW

**Comment by S1M0N38** [comment]
Thanks for the PR and for the screencast! I'm gonna clean it a bit and merge it soon 👍

**Comment by isaksamsten** [comment]
Cool. I'm using my own fork in the meantime. If you check, I've also added the option to have multiple prompts (i have one to paraphrase for example). So `:Dante paraphrase` uses the `paraphrase` prompt. If you like, I can open a pull-request for those changes also. This changes the `prompts` option to a dict with, e.g., `prompt = { paraphrase = "...", grammar = "...", default = "..."}` and uses `default` if no prompt is specified.

**Comment by S1M0N38** [comment]
I want to keep dante.nvim as simple as possible. But maybe being able to customize the prompt on the fly has its merits. The other option is to have a prompt that fit the majority of your use cases (e.g. Fix English in LaTeX and Markdown files). I'll take a look at your implementation but I make no promise.

**Comment by isaksamsten** [comment]
No problem. I can maintain a simple fork for my usecase if needed. It would be a configurable option to have multiple prompts, which i think can be nice since there are many text editing tasks an LLM can perform. Expand, summarize, grammar check, paraphrase, simplify, elaborate etc etc and I don't think one prompt will be enough for all of those.

**Comment by isaksamsten** [comment]
Your refactor is a great improvement over my lua hacking.

One thing though. I just merged your refactor with my branch, but i had to make the following changes:

```lua
local before_lines = vim.api.nvim_buf_get_lines(req_buf, 0, start_line - 1, true)
local lines = vim.api.nvim_buf_get_lines(req_buf, start_line - 1, end_line, true)
```

Full disclosure: I have only tried after resolving some merge confligs so i might have missed something.

**Pull request merged**
